version: '3'

services:
  react:
    build: 
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - "3044:3000"
    volumes:
      - /usr/src/app/node_modules
      - /mnt/c/ideaProjects/personal/docker-react-app:/usr/src/app
    stdin_open: true
  tests:
    build: 
      context: ./
      dockerfile: Dockerfile.dev    
    volumes:
      - /usr/src/app/node_modules
      - /mnt/c/ideaProjects/personal/docker-react-app:/usr/src/app
    command: ["npm","run","test"]